# Generated by Django 6.0.2 on 2026-03-05 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='analysis_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analysis.analysisrequest'),
        ),
        migrations.AddIndex(
            model_name='analysisrequest',
            index=models.Index(fields=['title'], name='analysis_an_title_a123c6_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrequest',
            index=models.Index(fields=['status'], name='analysis_an_status_02bdc7_idx'),
        ),
    ]
