# Generated by Django 6.0.2 on 2026-03-05 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('domain', models.CharField(max_length=255)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('robots_ok', models.BooleanField(default=True)),
                ('fetch_method', models.CharField(default='requests', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='analysis.analysisrequest')),
                ('text', models.TextField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('date', models.CharField(blank=True, max_length=64)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='scraping.sourcepage')),
            ],
        ),
    ]
